<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Menu seed.
 */
class MenuSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'parent_id' => NULL,
                'lft' => 1,
                'rght' => 2,
                'level' => 0,
                'icon' => '<i class="fa-solid fa-code"></i>',
                'controller' => 'Dashboards',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'Dashboard',
                'url' => '',
                'prefix' => '',
                'auth' => 1,
                'admin' => 0,
                'active' => 1,
                'disabled' => 0,
                'divider_before' => 0,
                'parent_separator' => 0,
                'division' => 0,
            ],
            [
                'id' => 2,
                'parent_id' => NULL,
                'lft' => 3,
                'rght' => 4,
                'level' => 0,
                'icon' => '<i class="fa-regular fa-circle-question"></i>',
                'controller' => 'Faqs',
                'action' => '',
                'target' => NULL,
                'name' => 'FAQs',
                'url' => '',
                'prefix' => '',
                'auth' => 0,
                'admin' => 0,
                'active' => 1,
                'disabled' => 0,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 3,
                'parent_id' => NULL,
                'lft' => 5,
                'rght' => 6,
                'level' => 0,
                'icon' => '<i class="fa-regular fa-message"></i>',
                'controller' => 'Contacts',
                'action' => 'Add',
                'target' => NULL,
                'name' => 'Contact Us',
                'url' => '',
                'prefix' => '',
                'auth' => 0,
                'admin' => 0,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 4,
                'parent_id' => NULL,
                'lft' => 7,
                'rght' => 14,
                'level' => 0,
                'icon' => '<i class="fa-solid fa-circle-info"></i>',
                'controller' => 'Pages',
                'action' => 'manual',
                'target' => NULL,
                'name' => 'Documentation',
                'url' => '',
                'prefix' => '',
                'auth' => 0,
                'admin' => 0,
                'active' => 1,
                'disabled' => 0,
                'divider_before' => 0,
                'parent_separator' => 1,
                'division' => 0,
            ],
            [
                'id' => 5,
                'parent_id' => NULL,
                'lft' => 15,
                'rght' => 16,
                'level' => 0,
                'icon' => '',
                'controller' => '',
                'action' => '',
                'target' => NULL,
                'name' => 'Administrator',
                'url' => '',
                'prefix' => NULL,
                'auth' => 0,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 1,
            ],
            [
                'id' => 6,
                'parent_id' => NULL,
                'lft' => 17,
                'rght' => 18,
                'level' => 0,
                'icon' => '<i class="fa-solid fa-gear"></i>',
                'controller' => 'Settings',
                'action' => 'Update',
                'target' => 'recrud',
                'name' => 'System Configuration',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 7,
                'parent_id' => NULL,
                'lft' => 19,
                'rght' => 20,
                'level' => 0,
                'icon' => '<i class="fa-solid fa-users-viewfinder"></i>',
                'controller' => 'Users',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'User Management',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 8,
                'parent_id' => NULL,
                'lft' => 21,
                'rght' => 22,
                'level' => 0,
                'icon' => '<i class="fa-solid fa-bars"></i>',
                'controller' => 'Menus',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'Menu Management',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => 0,
                'division' => 0,
            ],
            [
                'id' => 9,
                'parent_id' => NULL,
                'lft' => 23,
                'rght' => 24,
                'level' => 0,
                'icon' => '<i class="menu-icon fa-solid fa-list-check"></i>',
                'controller' => 'Todos',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'Todo List',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 10,
                'parent_id' => NULL,
                'lft' => 25,
                'rght' => 26,
                'level' => 0,
                'icon' => '<i class="fa-regular fa-message"></i>',
                'controller' => 'Contacts',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'Contact',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 11,
                'parent_id' => NULL,
                'lft' => 27,
                'rght' => 28,
                'level' => 0,
                'icon' => '<i class="menu-icon fa-solid fa-timeline"></i>',
                'controller' => 'AuditLogs',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'Audit Trail',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => NULL,
                'division' => 0,
            ],
            [
                'id' => 12,
                'parent_id' => NULL,
                'lft' => 29,
                'rght' => 30,
                'level' => 0,
                'icon' => '<i class="menu-icon fa-regular fa-circle-question"></i>',
                'controller' => 'Faqs',
                'action' => 'Index',
                'target' => NULL,
                'name' => 'FAQs',
                'url' => '',
                'prefix' => 'Admin',
                'auth' => 1,
                'admin' => 1,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => 0,
                'division' => 0,
            ],
            [
                'id' => 13,
                'parent_id' => 4,
                'lft' => 10,
                'rght' => 11,
                'level' => 1,
                'icon' => '<i class="fa-solid fa-code"></i>',
                'controller' => '',
                'action' => '',
                'target' => NULL,
                'name' => 'Code The Pixel',
                'url' => 'https://codethepixel.com/',
                'prefix' => '',
                'auth' => 0,
                'admin' => 0,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => 0,
                'division' => 0,
            ],
            [
                'id' => 14,
                'parent_id' => 4,
                'lft' => 8,
                'rght' => 9,
                'level' => 1,
                'icon' => '<i class="fa-regular fa-file-code"></i>',
                'controller' => 'Pages',
                'action' => 'manual',
                'target' => NULL,
                'name' => 'User Manual',
                'url' => '',
                'prefix' => '',
                'auth' => 0,
                'admin' => 0,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => 0,
                'division' => 0,
            ],
            [
                'id' => 15,
                'parent_id' => 4,
                'lft' => 12,
                'rght' => 13,
                'level' => 1,
                'icon' => '<i class="fa-brands fa-github"></i>',
                'controller' => '',
                'action' => '',
                'target' => NULL,
                'name' => 'Re-CRUD Github',
                'url' => 'https://github.com/Asyraf-wa/recrud',
                'prefix' => '',
                'auth' => 0,
                'admin' => 0,
                'active' => 1,
                'disabled' => NULL,
                'divider_before' => 0,
                'parent_separator' => 0,
                'division' => 0,
            ],
        ];

        $table = $this->table('menus');
        $table->insert($data)->save();
    }
}
